# Generated by Django 5.0.2 on 2024-04-09 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_profile_user_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile_user',
            name='is_author',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile_user',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
