# Generated by Django 5.0.2 on 2024-04-09 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_profile_user_is_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_user',
            name='is_author',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
